// AUTO-GENERATED by scripts/generate_data.py — do not edit by hand.
// Source of truth: ../../01_profile/profile.json
export const DATA = {
  "identity": {
    "name": "SAGAR CHAUDHARY",
    "first": "Sagar",
    "location": "Bengaluru, India",
    "area": "HSR Layout, Bengaluru",
    "email": "sagar16ch07@gmail.com",
    "phone": "+91 9225773462"
  },
  "links": {
    "linkedin": "https://www.linkedin.com/in/sagar-chaudhary777/",
    "github": "https://github.com/SAGARCHRY0777",
    "inferno_repo": "https://github.com/SAGARCHRY0777/inferno",
    "inferno_demo": "https://inferno-ny28.onrender.com/"
  },
  "headline": "AI Engineer | Industrial & Manufacturing AI | GenAI, RAG & Agentic Systems | MLOps",
  "availability": {
    "start": "2025-04",
    "notice": "20-45 days",
    "notice_full": "20-45 days (negotiable)",
    "mode": "Open to all - onsite, hybrid and fully remote",
    "locations": "Open to roles across India. Priority order: Bengaluru > Pune > Hyderabad > Mumbai > Gurugram/NCR.",
    "experience": "1 year 4 months (Apr 2025 - present, incl. 7-month internship converted to full-time)",
    "experience_start": "2025-04"
  },
  "summaries": {
    "master": "AI Engineer specializing in industrial and manufacturing AI. Builds end-to-end IT-OT data pipelines that ingest high-frequency plant sensor data in real time, trains deep-learning models (PyTorch, TensorFlow, CNNs, LSTM time-series, LiDAR-camera sensor fusion), and applies Generative AI - RAG (LangChain), agentic workflows (LangGraph, MCP), chunking strategies, prompt engineering, and prompt-to-template design - to turn operational data into business decisions. Ships to production with MLOps practices: Docker, Kubernetes with autoscaling, CI/CD, and full observability. Strong foundation in Python, PostgreSQL (SQL) and NoSQL databases, distributed systems, and scalable event-driven architectures.",
    "industrial": "AI Engineer specializing in industrial and manufacturing AI (Industry 4.0 / IIoT). Architects end-to-end IT-OT data pipelines that ingest high-frequency plant and engine sensor data over raw TCP/IP in real time, and trains deep-learning time-series models (LSTM, PyTorch) for trend forecasting, anomaly detection and predictive maintenance on live test runs. Designs event-driven publish-subscribe architectures that decouple ingestion, processing and streaming so new sensor types are added by configuration, not code. Applies Generative AI - RAG over technical test reports and agentic natural-language-to-SQL workflows - to put operational data directly in the hands of plant engineers. Ships to production with Docker, Kubernetes autoscaling, CI/CD and full observability.",
    "genai": "AI Engineer specializing in Generative AI and agentic systems. Builds production RAG pipelines end to end - chunking strategy, embedding selection (Nomic, Gemini), ChromaDB vector stores, cross-encoder reranking and prompt-to-template design - and stateful multi-step agents with LangGraph and MCP that route between tools for natural-language-to-SQL and automated report generation. Serves LLMs across Ollama, OpenAI and Gemini behind a streaming FastAPI layer. Backs it with real deep-learning depth (PyTorch, LSTM, CNNs, BERT) and production MLOps: Docker, Kubernetes with KEDA autoscaling, CI/CD, Prometheus and OpenTelemetry observability.",
    "cv": "Computer Vision / Perception Engineer with production deep-learning experience across autonomous-driving and ADAS systems. Built multi-modal 3D object detection fusing LiDAR point clouds (SFA3D) with CNN-based camera detections (YOLOv8) using confidence-weighted IoU association - 92.44% / 80.23% AP (easy / hard) on the KITTI benchmark - including LiDAR-to-camera extrinsic calibration via RANSAC/PROSAC and Gaussian/Weighted NMS post-processing. Shipped a production driver foot-monitoring ADAS system combining segmentation, keypoint and object detection with ZoeDepth monocular depth inference. Strong PyTorch, OpenCV and Open3D foundation, with the MLOps skills (Docker, Kubernetes, ONNX Runtime, CI/CD) to take models from benchmark to production.",
    "mlops": "ML Platform / MLOps Engineer who builds the infrastructure that serves models at scale. Designed and shipped a horizontally-scalable inference platform - stateless async FastAPI gateway, Redis-Streams broker, shared-nothing worker pool - with dynamic request batching, backpressure with hysteresis, at-least-once delivery via consumer-group reclaim, and O(1) WebSocket result routing that lifted a 120-client ceiling. Runs it on Kubernetes with KEDA queue-depth autoscaling, GitHub Actions CI, Prometheus metrics, OpenTelemetry tracing and ONNX Runtime serving. Backed by real modelling depth in PyTorch (LSTM, CNNs) and production Python/Go distributed-systems experience.",
    "backend": "Backend Engineer building distributed, event-driven systems in Python and Go. Architected real-time data pipelines ingesting high-frequency sensor streams over raw TCP/IP sockets and delivering them to clients over WebSockets at sub-second latency, with asynchronous processing and multithreaded batched writes that sustain continuous high-volume load. Designs microservice and publish-subscribe architectures, models normalized PostgreSQL schemas alongside NoSQL stores, and secures APIs with JWT and role-based access control. Ships with Docker, Kubernetes, CI/CD and full observability - plus applied ML and GenAI experience for teams building AI-backed products."
  },
  "readouts": [
    {
      "v": "",
      "u": "mo",
      "live": "experience_months",
      "k": "Production AI experience",
      "src": "answer_bank.experience_start"
    },
    {
      "v": "6",
      "u": "",
      "k": "Systems shipped in role",
      "src": "experience[].projects"
    },
    {
      "v": "7",
      "u": "",
      "k": "Model types served — Inferno",
      "src": "projects.inferno bullet 8"
    },
    {
      "v": "92.44",
      "u": "%",
      "k": "AP (easy) — LiDAR-camera fusion",
      "src": "experience.intern fusion bullet 2"
    }
  ],
  "systems": [
    {
      "name": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "qualifier": "(Industrial IT-OT System)",
      "org": "Deevia Software",
      "role": "Graduate Trainee Engineer",
      "dates": "Nov 2025 - Present",
      "kind": "work",
      "tags": [
        "industrial",
        "genai",
        "backend",
        "ml"
      ],
      "stack": [
        "Python",
        "FastAPI",
        "LangChain",
        "LangGraph",
        "LSTM (PyTorch)",
        "RAG",
        "ChromaDB",
        "Ollama",
        "OpenAI",
        "Gemini",
        "WebSockets",
        "TCP/IP Sockets",
        "PostgreSQL",
        "React.js",
        "TypeScript",
        "Redux Toolkit",
        "Docker",
        "JWT",
        "RBAC"
      ],
      "points": [
        {
          "t": "Architected an end-to-end IT-OT data pipeline for an engine test facility - ingesting high-frequency industrial sensor data over raw TCP/IP sockets and streaming it to live dashboards via WebSockets at sub-second latency.",
          "tags": [
            "industrial",
            "backend"
          ],
          "w": 10
        },
        {
          "t": "Trained LSTM deep-learning models on engine sensor time-series for trend forecasting, anomaly detection, and predictive-maintenance insights during live test runs.",
          "tags": [
            "industrial",
            "ml",
            "dl"
          ],
          "w": 10
        },
        {
          "t": "Built a LangChain-based RAG assistant over test reports - designed the chunking strategy, prompt-to-template pipeline, Nomic/Gemini embeddings into a ChromaDB vector store, and a reranking stage serving LLMs via Ollama, OpenAI, and Gemini - enabling natural-language querying of historical test data and eliminating manual report lookups.",
          "tags": [
            "genai"
          ],
          "w": 10
        },
        {
          "t": "Developed agentic AI workflows with LangGraph - a stateful multi-step agent that routes between tools for natural-language-to-SQL querying of test data and automated test-report generation and summarization.",
          "tags": [
            "genai"
          ],
          "w": 10
        },
        {
          "t": "Designed an event-driven publish-subscribe architecture that decoupled ingestion, processing, and streaming services, so new sensor types are added through configuration rather than code changes.",
          "tags": [
            "backend",
            "industrial"
          ],
          "w": 9
        },
        {
          "t": "Optimized ingestion with asynchronous processing and multithreaded batched database writes, sustaining continuous high-volume sensor load without memory backpressure.",
          "tags": [
            "backend",
            "industrial"
          ],
          "w": 8
        },
        {
          "t": "Modeled normalized PostgreSQL schemas and tuned SQL queries for fast retrieval of historical test runs, ensuring data integrity across ingestion and storage layers.",
          "tags": [
            "backend",
            "data"
          ],
          "w": 6
        },
        {
          "t": "Secured the platform with JWT authentication and role-based access control enforcing per-role permissions across all endpoints.",
          "tags": [
            "backend"
          ],
          "w": 5
        },
        {
          "t": "Implemented automated crash-recovery and graceful-shutdown handling for clean restarts without data loss.",
          "tags": [
            "backend",
            "mlops"
          ],
          "w": 5
        },
        {
          "t": "Built a React + TypeScript front-end with Redux Toolkit for live dashboards and trend analytics with lag-free real-time updates for engineers and business users.",
          "tags": [
            "frontend"
          ],
          "w": 4
        }
      ],
      "links": []
    },
    {
      "name": "Multi-Vendor Camera Device Management Framework",
      "qualifier": "",
      "org": "Deevia Software",
      "role": "Graduate Trainee Engineer",
      "dates": "Nov 2025 - Present",
      "kind": "work",
      "tags": [
        "backend",
        "cv",
        "data"
      ],
      "stack": [
        "Python",
        "FastAPI",
        "PostgreSQL",
        "MongoDB (NoSQL)",
        "React",
        "Docker",
        "CI/CD",
        "OOP Design Patterns"
      ],
      "points": [
        {
          "t": "Built a device management framework using object-oriented design - abstract base classes and interface layers - to abstract camera hardware, enabling drop-in integration of multiple camera vendors without backend changes.",
          "tags": [
            "backend",
            "cv"
          ],
          "w": 9
        },
        {
          "t": "Developed a FastAPI backend exposing REST endpoints for device registration, configuration management, and real-time status monitoring across distributed devices.",
          "tags": [
            "backend"
          ],
          "w": 7
        },
        {
          "t": "Designed a dual-database layer - PostgreSQL for relational device records and MongoDB (NoSQL) for heterogeneous, schema-less device configurations - to handle structured and unstructured data efficiently.",
          "tags": [
            "backend",
            "data"
          ],
          "w": 7
        },
        {
          "t": "Containerized the full stack with Docker and automated build/deploy through CI/CD pipelines for reproducible releases.",
          "tags": [
            "mlops"
          ],
          "w": 6
        },
        {
          "t": "Built a React dashboard for device monitoring, configuration, and analytics with role-based access control.",
          "tags": [
            "frontend"
          ],
          "w": 4
        }
      ],
      "links": []
    },
    {
      "name": "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "qualifier": "",
      "org": "Deevia Software",
      "role": "Machine Learning Intern",
      "dates": "Apr 2025 - Nov 2025",
      "kind": "work",
      "tags": [
        "cv",
        "dl"
      ],
      "stack": [
        "Python",
        "PyTorch",
        "YOLOv8 (CNN)",
        "SFA3D",
        "OpenCV",
        "Open3D",
        "NumPy",
        "SLAM",
        "RANSAC/PROSAC",
        "Docker"
      ],
      "points": [
        {
          "t": "Built a multi-modal 3D object detection system fusing LiDAR point-cloud detections (SFA3D) with CNN-based 2D camera detections (YOLOv8) for robust perception in autonomous-driving scenes.",
          "tags": [
            "cv",
            "dl"
          ],
          "w": 10
        },
        {
          "t": "Designed a confidence-weighted fusion algorithm that combines per-sensor detections by IoU association, improving accuracy and robustness over single-sensor baselines - 92.44% / 80.23% AP (easy / hard) on the KITTI benchmark.",
          "tags": [
            "cv",
            "dl"
          ],
          "w": 10
        },
        {
          "t": "Implemented LiDAR-to-camera extrinsic calibration using RANSAC/PROSAC for robust, drift-resistant sensor alignment.",
          "tags": [
            "cv"
          ],
          "w": 9
        },
        {
          "t": "Built a post-processing pipeline with Gaussian NMS and Weighted NMS to merge overlapping boxes and refine final detections.",
          "tags": [
            "cv"
          ],
          "w": 8
        },
        {
          "t": "Developed visualization tooling with multi-model attribution and runtime performance statistics for debugging and fusion analysis.",
          "tags": [
            "cv"
          ],
          "w": 5
        },
        {
          "t": "Containerized training and inference with Docker for reproducible benchmark runs.",
          "tags": [
            "mlops"
          ],
          "w": 5
        }
      ],
      "links": []
    },
    {
      "name": "Distributed Multi-Sensor Video Analytics Platform",
      "qualifier": "",
      "org": "Deevia Software",
      "role": "Machine Learning Intern",
      "dates": "Apr 2025 - Nov 2025",
      "kind": "work",
      "tags": [
        "backend",
        "cv",
        "mlops"
      ],
      "stack": [
        "Go",
        "Python",
        "FastAPI",
        "REST APIs",
        "WebSockets",
        "AWS",
        "PostgreSQL",
        "Docker",
        "Microservices",
        "OpenCV"
      ],
      "points": [
        {
          "t": "Designed a distributed microservices architecture on AWS separating ingestion, processing, and streaming layers for scalable multi-camera plus sensor pipelines.",
          "tags": [
            "backend",
            "mlops"
          ],
          "w": 9
        },
        {
          "t": "Built a dual-backend system: Go services handling real-time API orchestration and request validation, with Python services running compute-intensive video processing.",
          "tags": [
            "backend"
          ],
          "w": 9
        },
        {
          "t": "Implemented timestamp synchronization to align video frames with multi-modal sensor streams (accelerometer, velocity, gyroscope) for precise temporal correlation.",
          "tags": [
            "cv",
            "industrial"
          ],
          "w": 8
        },
        {
          "t": "Built a multi-format ingestion pipeline supporting heterogeneous camera systems with mixed inputs (video, CSV, binary sensor files).",
          "tags": [
            "backend",
            "cv"
          ],
          "w": 6
        },
        {
          "t": "Used WebSocket-based inter-service messaging for low-latency async job status and result streaming; containerized all services with Docker for reproducible deployment across environments.",
          "tags": [
            "backend",
            "mlops"
          ],
          "w": 6
        }
      ],
      "links": []
    },
    {
      "name": "Foot Monitoring System (ADAS)",
      "qualifier": "",
      "org": "Deevia Software",
      "role": "Machine Learning Intern",
      "dates": "Apr 2025 - Nov 2025",
      "kind": "work",
      "tags": [
        "cv",
        "dl"
      ],
      "stack": [
        "Python",
        "PyTorch",
        "YOLOv11",
        "Detectron2",
        "ZoeDepth",
        "OpenCV",
        "FastAPI",
        "React",
        "PostgreSQL",
        "AWS"
      ],
      "points": [
        {
          "t": "Built a production computer-vision system detecting driver pedal interactions (accelerator, brake, clutch) by combining segmentation, keypoint detection, and object detection deep-learning models.",
          "tags": [
            "cv",
            "dl"
          ],
          "w": 10
        },
        {
          "t": "Developed pedal-position estimation and monocular depth inference using ZoeDepth with custom logic to classify pedal depression and distinct foot actions.",
          "tags": [
            "cv",
            "dl"
          ],
          "w": 9
        },
        {
          "t": "Automated data collection, labeling, and continuous model retraining using Dockerized microservices and open-source annotation tools (LabelMe, LabelImg).",
          "tags": [
            "mlops",
            "cv"
          ],
          "w": 8
        },
        {
          "t": "Built a FastAPI backend with REST endpoints for data access, annotation workflows, and real-time inference, with abstract interfaces for multi-camera modularity.",
          "tags": [
            "backend",
            "cv"
          ],
          "w": 6
        },
        {
          "t": "Built a React front-end with live camera-feed monitoring and actionable safety visualizations.",
          "tags": [
            "frontend"
          ],
          "w": 4
        }
      ],
      "links": []
    },
    {
      "name": "Sales Trend Analysis & Time-Series Forecasting",
      "qualifier": "",
      "org": "Deevia Software",
      "role": "Machine Learning Intern",
      "dates": "Apr 2025 - Nov 2025",
      "kind": "work",
      "tags": [
        "ml",
        "data"
      ],
      "stack": [
        "Python",
        "Pandas",
        "NumPy",
        "Scikit-Learn",
        "Statsmodels",
        "ARIMA",
        "Matplotlib",
        "Seaborn"
      ],
      "points": [
        {
          "t": "Built an auto-ARIMA time-series forecasting model with statsmodels and automated parameter selection for reliable short-term revenue prediction for business stakeholders.",
          "tags": [
            "ml"
          ],
          "w": 8
        },
        {
          "t": "Performed exploratory analysis on sales transaction data using correlation matrices, time-series decomposition, and distribution analysis to identify seasonal demand patterns.",
          "tags": [
            "ml",
            "data"
          ],
          "w": 7
        },
        {
          "t": "Detected and flagged revenue outliers using IQR and z-score methods to surface irregular sales events affecting forecasts.",
          "tags": [
            "ml",
            "data"
          ],
          "w": 6
        }
      ],
      "links": []
    },
    {
      "name": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "qualifier": "",
      "org": "Independent",
      "role": "Personal system",
      "dates": "",
      "kind": "personal",
      "tags": [
        "mlops",
        "backend",
        "genai"
      ],
      "stack": [
        "Python",
        "FastAPI",
        "Redis (Streams + Pub/Sub)",
        "WebSockets",
        "asyncio",
        "PyTorch",
        "ONNX Runtime",
        "YOLOv8",
        "faster-whisper",
        "Sentence-Transformers (RAG)",
        "MCP (Agentic AI)",
        "Prometheus",
        "OpenTelemetry",
        "React",
        "TypeScript",
        "Docker",
        "Kubernetes",
        "KEDA",
        "GitHub Actions"
      ],
      "points": [
        {
          "t": "Built a horizontally-scalable model-serving platform - a stateless async FastAPI gateway, a Redis-Streams broker, and a pool of shared-nothing worker processes - that batches inference requests and streams results back over WebSockets to a live ops dashboard, solving the core serving problem of high throughput and low-latency real-time delivery.",
          "tags": [
            "mlops",
            "backend"
          ],
          "w": 10
        },
        {
          "t": "Shipped an agentic AI layer: an MCP agent server exposing platform tools to LLM agents (tool-use and API collaboration), streaming local-LLM chat (SSE), and a RAG pipeline with bi-encoder retrieval, cross-encoder reranking, and cited answers.",
          "tags": [
            "genai"
          ],
          "w": 10
        },
        {
          "t": "Applied MLOps end to end - centralized config/contracts spine (pydantic-settings), custom Prometheus collector, OpenTelemetry tracing, structured logging, a Dockerized stack, Kubernetes manifests with KEDA queue-depth autoscaling, green GitHub Actions CI, and a live production deployment.",
          "tags": [
            "mlops"
          ],
          "w": 10
        },
        {
          "t": "Implemented dynamic request batching (size-or-timeout window) that amortizes per-call model overhead and keeps the GPU/CPU saturated - raising throughput under load while capping tail latency at the batch-wait window, with no manual tuning.",
          "tags": [
            "mlops",
            "backend"
          ],
          "w": 9
        },
        {
          "t": "Engineered backpressure with hysteresis (HTTP 429 + Retry-After, dual high/low water-marks) so the platform sheds load and stays stable under overload instead of collapsing into latency spikes and OOM.",
          "tags": [
            "backend",
            "mlops"
          ],
          "w": 9
        },
        {
          "t": "Guaranteed zero job loss using Redis Streams consumer groups with a publish-before-ack ordering - dead-worker jobs are reclaimed via XPENDING/XCLAIM (at-least-once delivery with idempotent, TTL-bounded result keys).",
          "tags": [
            "backend",
            "mlops"
          ],
          "w": 9
        },
        {
          "t": "Scaled WebSocket result delivery to O(1) Redis connections via a single-connection PSUBSCRIBE result router, eliminating the connection-pool exhaustion that capped the naive design at ~120 concurrent clients.",
          "tags": [
            "backend"
          ],
          "w": 8
        },
        {
          "t": "Generalized the system with a config-driven, model-agnostic plugin registry serving 7 model types - YOLOv8 detection, Whisper transcription, ONNX/HuggingFace classification, and RAG question-answering.",
          "tags": [
            "mlops",
            "cv",
            "genai"
          ],
          "w": 8
        }
      ],
      "links": [
        {
          "text": "Live Demo",
          "url": "https://inferno-ny28.onrender.com/"
        },
        {
          "text": "GitHub",
          "url": "https://github.com/SAGARCHRY0777/inferno"
        }
      ]
    },
    {
      "name": "Disaster Tweet Classification",
      "qualifier": "",
      "org": "Independent",
      "role": "Personal system",
      "dates": "",
      "kind": "personal",
      "tags": [
        "ml",
        "genai",
        "dl"
      ],
      "stack": [
        "Python",
        "NLTK",
        "Scikit-Learn",
        "TensorFlow/Keras",
        "BERT",
        "TF-IDF"
      ],
      "points": [
        {
          "t": "Benchmarked standalone TF-IDF and BERT models, then built a hybrid classifier combining BERT embeddings with TF-IDF features - 92.8% accuracy / 91% F1, outperforming single-model baselines.",
          "tags": [
            "ml",
            "dl"
          ],
          "w": 9
        },
        {
          "t": "Collected real-time tweet data via the Twitter API and preprocessed noisy social text with tokenization, lemmatization, and stopword removal to build a clean training corpus.",
          "tags": [
            "ml",
            "data"
          ],
          "w": 7
        }
      ],
      "links": []
    },
    {
      "name": "Customer Churn Prediction",
      "qualifier": "",
      "org": "Independent",
      "role": "Personal system",
      "dates": "",
      "kind": "personal",
      "tags": [
        "ml",
        "data"
      ],
      "stack": [
        "Python",
        "Pandas",
        "Scikit-Learn",
        "XGBoost",
        "LightGBM",
        "AdaBoost",
        "Optuna",
        "SMOTE"
      ],
      "points": [
        {
          "t": "Handled class imbalance with SMOTE and tuned hyperparameters with Optuna - 94.6% accuracy, 0.96 AUC-ROC, 93.2% precision.",
          "tags": [
            "ml"
          ],
          "w": 9
        },
        {
          "t": "Benchmarked XGBoost, LightGBM, and AdaBoost with k-fold cross-validation, selecting the best ensemble on AUC-ROC and precision.",
          "tags": [
            "ml"
          ],
          "w": 8
        },
        {
          "t": "Analyzed feature importance to surface top churn drivers (contract type, tenure, monthly charges) for stakeholder dashboards.",
          "tags": [
            "ml",
            "data"
          ],
          "w": 6
        }
      ],
      "links": []
    }
  ],
  "caps": [
    {
      "key": "genai",
      "label": "Generative AI & Agentic",
      "items": [
        "LangChain",
        "LangGraph",
        "RAG",
        "agentic AI (tool-use agents",
        "MCP)",
        "chunking strategies",
        "prompt engineering",
        "prompt-to-template design",
        "rerankers",
        "vector search (ChromaDB)",
        "LLM & embedding APIs (OpenAI",
        "Gemini",
        "Ollama",
        "Nomic)"
      ]
    },
    {
      "key": "ml",
      "label": "Machine Learning",
      "items": [
        "classification",
        "regression",
        "time-series forecasting (LSTM",
        "ARIMA)",
        "ensembles (XGBoost",
        "LightGBM",
        "AdaBoost)",
        "feature engineering",
        "data cleaning & pre-processing",
        "SMOTE",
        "Optuna",
        "Scikit-Learn",
        "Pandas",
        "NumPy",
        "Statsmodels"
      ]
    },
    {
      "key": "dl",
      "label": "Deep Learning",
      "items": [
        "PyTorch",
        "TensorFlow/Keras",
        "CNNs (YOLO",
        "Detectron2",
        "ZoeDepth)",
        "LSTM/RNN time-series models",
        "BERT/Transformers",
        "transfer learning",
        "LiDAR-camera sensor fusion",
        "OpenCV",
        "Open3D"
      ]
    },
    {
      "key": "mlops",
      "label": "MLOps & Deployment",
      "items": [
        "Docker",
        "Kubernetes",
        "KEDA autoscaling",
        "CI/CD (GitHub Actions)",
        "Prometheus",
        "OpenTelemetry",
        "ONNX Runtime model serving",
        "structured logging",
        "monitoring",
        "crash-recovery design"
      ]
    },
    {
      "key": "backend",
      "label": "Backend & Data Pipelines",
      "items": [
        "Python",
        "Go",
        "Java",
        "FastAPI",
        "REST APIs",
        "WebSockets",
        "TCP/IP sockets",
        "microservices",
        "event-driven pub-sub",
        "Redis Streams",
        "asyncio",
        "JWT",
        "RBAC"
      ]
    },
    {
      "key": "data",
      "label": "Databases & Cloud",
      "items": [
        "PostgreSQL (SQL)",
        "NoSQL (MongoDB)",
        "MySQL",
        "ChromaDB",
        "AWS",
        "Linux",
        "Git"
      ]
    },
    {
      "key": "frontend",
      "label": "Frontend",
      "items": [
        "React.js",
        "TypeScript",
        "Redux Toolkit",
        "HTML",
        "CSS"
      ]
    },
    {
      "key": "core",
      "label": "Core CS",
      "items": [
        "Data Structures",
        "OOP",
        "Distributed Systems",
        "System Design",
        "Concurrency",
        "Operating Systems",
        "Computer Networks"
      ]
    }
  ],
  "timeline": [
    {
      "when": "Dec 2021 - Jul 2025",
      "what": "Bangalore Institute of Technology",
      "note": "B.E. in Information Science and Engineering (CGPA: 8.6)"
    },
    {
      "when": "2024",
      "what": "Top 10 of 150 teams — HumanAIze YouData.ai",
      "note": "Built a scalable NLP pipeline for document classification."
    },
    {
      "when": "2024",
      "what": "5th place — CODE RED 24-hour hackathon",
      "note": "Led a team of 4 building marine-life classification with CNNs and transfer learning."
    },
    {
      "when": "Apr 2025 - Nov 2025",
      "what": "Machine Learning Intern — Deevia Software",
      "note": "Perception and distributed video analytics: LiDAR-camera fusion, ADAS foot monitoring, multi-sensor pipelines on AWS."
    },
    {
      "when": "Nov 2025 - Present",
      "what": "Graduate Trainee Engineer — Deevia Software",
      "note": "Internship converted to full-time. Owns the engine test-bed IT-OT platform end to end."
    }
  ],
  "facts": [
    {
      "t": "Architected an end-to-end IT-OT data pipeline for an engine test facility - ingesting high-frequency industrial sensor data over raw TCP/IP sockets and streaming it to live dashboards via WebSockets at sub-second latency.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Trained LSTM deep-learning models on engine sensor time-series for trend forecasting, anomaly detection, and predictive-maintenance insights during live test runs.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "dl",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Built a LangChain-based RAG assistant over test reports - designed the chunking strategy, prompt-to-template pipeline, Nomic/Gemini embeddings into a ChromaDB vector store, and a reranking stage serving LLMs via Ollama, OpenAI, and Gemini - enabling natural-language querying of historical test data and eliminating manual report lookups.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Developed agentic AI workflows with LangGraph - a stateful multi-step agent that routes between tools for natural-language-to-SQL querying of test data and automated test-report generation and summarization.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Designed an event-driven publish-subscribe architecture that decoupled ingestion, processing, and streaming services, so new sensor types are added through configuration rather than code changes.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Optimized ingestion with asynchronous processing and multithreaded batched database writes, sustaining continuous high-volume sensor load without memory backpressure.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Modeled normalized PostgreSQL schemas and tuned SQL queries for fast retrieval of historical test runs, ensuring data integrity across ingestion and storage layers.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "data",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Secured the platform with JWT authentication and role-based access control enforcing per-role permissions across all endpoints.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Implemented automated crash-recovery and graceful-shutdown handling for clean restarts without data loss.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "genai",
        "industrial",
        "ml",
        "mlops"
      ]
    },
    {
      "t": "Built a React + TypeScript front-end with Redux Toolkit for live dashboards and trend analytics with lag-free real-time updates for engineers and business users.",
      "src": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "tags": [
        "backend",
        "frontend",
        "genai",
        "industrial",
        "ml"
      ]
    },
    {
      "t": "Built a device management framework using object-oriented design - abstract base classes and interface layers - to abstract camera hardware, enabling drop-in integration of multiple camera vendors without backend changes.",
      "src": "Multi-Vendor Camera Device Management Framework",
      "tags": [
        "backend",
        "cv",
        "data"
      ]
    },
    {
      "t": "Developed a FastAPI backend exposing REST endpoints for device registration, configuration management, and real-time status monitoring across distributed devices.",
      "src": "Multi-Vendor Camera Device Management Framework",
      "tags": [
        "backend",
        "cv",
        "data"
      ]
    },
    {
      "t": "Designed a dual-database layer - PostgreSQL for relational device records and MongoDB (NoSQL) for heterogeneous, schema-less device configurations - to handle structured and unstructured data efficiently.",
      "src": "Multi-Vendor Camera Device Management Framework",
      "tags": [
        "backend",
        "cv",
        "data"
      ]
    },
    {
      "t": "Containerized the full stack with Docker and automated build/deploy through CI/CD pipelines for reproducible releases.",
      "src": "Multi-Vendor Camera Device Management Framework",
      "tags": [
        "backend",
        "cv",
        "data",
        "mlops"
      ]
    },
    {
      "t": "Built a React dashboard for device monitoring, configuration, and analytics with role-based access control.",
      "src": "Multi-Vendor Camera Device Management Framework",
      "tags": [
        "backend",
        "cv",
        "data",
        "frontend"
      ]
    },
    {
      "t": "Built a multi-modal 3D object detection system fusing LiDAR point-cloud detections (SFA3D) with CNN-based 2D camera detections (YOLOv8) for robust perception in autonomous-driving scenes.",
      "src": "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "tags": [
        "cv",
        "dl"
      ]
    },
    {
      "t": "Designed a confidence-weighted fusion algorithm that combines per-sensor detections by IoU association, improving accuracy and robustness over single-sensor baselines - 92.44% / 80.23% AP (easy / hard) on the KITTI benchmark.",
      "src": "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "tags": [
        "cv",
        "dl"
      ]
    },
    {
      "t": "Implemented LiDAR-to-camera extrinsic calibration using RANSAC/PROSAC for robust, drift-resistant sensor alignment.",
      "src": "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "tags": [
        "cv",
        "dl"
      ]
    },
    {
      "t": "Built a post-processing pipeline with Gaussian NMS and Weighted NMS to merge overlapping boxes and refine final detections.",
      "src": "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "tags": [
        "cv",
        "dl"
      ]
    },
    {
      "t": "Developed visualization tooling with multi-model attribution and runtime performance statistics for debugging and fusion analysis.",
      "src": "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "tags": [
        "cv",
        "dl"
      ]
    },
    {
      "t": "Containerized training and inference with Docker for reproducible benchmark runs.",
      "src": "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "tags": [
        "cv",
        "dl",
        "mlops"
      ]
    },
    {
      "t": "Designed a distributed microservices architecture on AWS separating ingestion, processing, and streaming layers for scalable multi-camera plus sensor pipelines.",
      "src": "Distributed Multi-Sensor Video Analytics Platform",
      "tags": [
        "backend",
        "cv",
        "mlops"
      ]
    },
    {
      "t": "Built a dual-backend system: Go services handling real-time API orchestration and request validation, with Python services running compute-intensive video processing.",
      "src": "Distributed Multi-Sensor Video Analytics Platform",
      "tags": [
        "backend",
        "cv",
        "mlops"
      ]
    },
    {
      "t": "Implemented timestamp synchronization to align video frames with multi-modal sensor streams (accelerometer, velocity, gyroscope) for precise temporal correlation.",
      "src": "Distributed Multi-Sensor Video Analytics Platform",
      "tags": [
        "backend",
        "cv",
        "industrial",
        "mlops"
      ]
    },
    {
      "t": "Built a multi-format ingestion pipeline supporting heterogeneous camera systems with mixed inputs (video, CSV, binary sensor files).",
      "src": "Distributed Multi-Sensor Video Analytics Platform",
      "tags": [
        "backend",
        "cv",
        "mlops"
      ]
    },
    {
      "t": "Used WebSocket-based inter-service messaging for low-latency async job status and result streaming; containerized all services with Docker for reproducible deployment across environments.",
      "src": "Distributed Multi-Sensor Video Analytics Platform",
      "tags": [
        "backend",
        "cv",
        "mlops"
      ]
    },
    {
      "t": "Built a production computer-vision system detecting driver pedal interactions (accelerator, brake, clutch) by combining segmentation, keypoint detection, and object detection deep-learning models.",
      "src": "Foot Monitoring System (ADAS)",
      "tags": [
        "cv",
        "dl"
      ]
    },
    {
      "t": "Developed pedal-position estimation and monocular depth inference using ZoeDepth with custom logic to classify pedal depression and distinct foot actions.",
      "src": "Foot Monitoring System (ADAS)",
      "tags": [
        "cv",
        "dl"
      ]
    },
    {
      "t": "Automated data collection, labeling, and continuous model retraining using Dockerized microservices and open-source annotation tools (LabelMe, LabelImg).",
      "src": "Foot Monitoring System (ADAS)",
      "tags": [
        "cv",
        "dl",
        "mlops"
      ]
    },
    {
      "t": "Built a FastAPI backend with REST endpoints for data access, annotation workflows, and real-time inference, with abstract interfaces for multi-camera modularity.",
      "src": "Foot Monitoring System (ADAS)",
      "tags": [
        "backend",
        "cv",
        "dl"
      ]
    },
    {
      "t": "Built a React front-end with live camera-feed monitoring and actionable safety visualizations.",
      "src": "Foot Monitoring System (ADAS)",
      "tags": [
        "cv",
        "dl",
        "frontend"
      ]
    },
    {
      "t": "Built an auto-ARIMA time-series forecasting model with statsmodels and automated parameter selection for reliable short-term revenue prediction for business stakeholders.",
      "src": "Sales Trend Analysis & Time-Series Forecasting",
      "tags": [
        "data",
        "ml"
      ]
    },
    {
      "t": "Performed exploratory analysis on sales transaction data using correlation matrices, time-series decomposition, and distribution analysis to identify seasonal demand patterns.",
      "src": "Sales Trend Analysis & Time-Series Forecasting",
      "tags": [
        "data",
        "ml"
      ]
    },
    {
      "t": "Detected and flagged revenue outliers using IQR and z-score methods to surface irregular sales events affecting forecasts.",
      "src": "Sales Trend Analysis & Time-Series Forecasting",
      "tags": [
        "data",
        "ml"
      ]
    },
    {
      "t": "Built a horizontally-scalable model-serving platform - a stateless async FastAPI gateway, a Redis-Streams broker, and a pool of shared-nothing worker processes - that batches inference requests and streams results back over WebSockets to a live ops dashboard, solving the core serving problem of high throughput and low-latency real-time delivery.",
      "src": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "tags": [
        "backend",
        "genai",
        "mlops"
      ]
    },
    {
      "t": "Shipped an agentic AI layer: an MCP agent server exposing platform tools to LLM agents (tool-use and API collaboration), streaming local-LLM chat (SSE), and a RAG pipeline with bi-encoder retrieval, cross-encoder reranking, and cited answers.",
      "src": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "tags": [
        "backend",
        "genai",
        "mlops"
      ]
    },
    {
      "t": "Applied MLOps end to end - centralized config/contracts spine (pydantic-settings), custom Prometheus collector, OpenTelemetry tracing, structured logging, a Dockerized stack, Kubernetes manifests with KEDA queue-depth autoscaling, green GitHub Actions CI, and a live production deployment.",
      "src": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "tags": [
        "backend",
        "genai",
        "mlops"
      ]
    },
    {
      "t": "Implemented dynamic request batching (size-or-timeout window) that amortizes per-call model overhead and keeps the GPU/CPU saturated - raising throughput under load while capping tail latency at the batch-wait window, with no manual tuning.",
      "src": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "tags": [
        "backend",
        "genai",
        "mlops"
      ]
    },
    {
      "t": "Engineered backpressure with hysteresis (HTTP 429 + Retry-After, dual high/low water-marks) so the platform sheds load and stays stable under overload instead of collapsing into latency spikes and OOM.",
      "src": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "tags": [
        "backend",
        "genai",
        "mlops"
      ]
    },
    {
      "t": "Guaranteed zero job loss using Redis Streams consumer groups with a publish-before-ack ordering - dead-worker jobs are reclaimed via XPENDING/XCLAIM (at-least-once delivery with idempotent, TTL-bounded result keys).",
      "src": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "tags": [
        "backend",
        "genai",
        "mlops"
      ]
    },
    {
      "t": "Scaled WebSocket result delivery to O(1) Redis connections via a single-connection PSUBSCRIBE result router, eliminating the connection-pool exhaustion that capped the naive design at ~120 concurrent clients.",
      "src": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "tags": [
        "backend",
        "genai",
        "mlops"
      ]
    },
    {
      "t": "Generalized the system with a config-driven, model-agnostic plugin registry serving 7 model types - YOLOv8 detection, Whisper transcription, ONNX/HuggingFace classification, and RAG question-answering.",
      "src": "Inferno - Distributed ML Inference & Agentic AI Platform",
      "tags": [
        "backend",
        "cv",
        "genai",
        "mlops"
      ]
    },
    {
      "t": "Benchmarked standalone TF-IDF and BERT models, then built a hybrid classifier combining BERT embeddings with TF-IDF features - 92.8% accuracy / 91% F1, outperforming single-model baselines.",
      "src": "Disaster Tweet Classification",
      "tags": [
        "dl",
        "genai",
        "ml"
      ]
    },
    {
      "t": "Collected real-time tweet data via the Twitter API and preprocessed noisy social text with tokenization, lemmatization, and stopword removal to build a clean training corpus.",
      "src": "Disaster Tweet Classification",
      "tags": [
        "data",
        "dl",
        "genai",
        "ml"
      ]
    },
    {
      "t": "Handled class imbalance with SMOTE and tuned hyperparameters with Optuna - 94.6% accuracy, 0.96 AUC-ROC, 93.2% precision.",
      "src": "Customer Churn Prediction",
      "tags": [
        "data",
        "ml"
      ]
    },
    {
      "t": "Benchmarked XGBoost, LightGBM, and AdaBoost with k-fold cross-validation, selecting the best ensemble on AUC-ROC and precision.",
      "src": "Customer Churn Prediction",
      "tags": [
        "data",
        "ml"
      ]
    },
    {
      "t": "Analyzed feature importance to surface top churn drivers (contract type, tenure, monthly charges) for stakeholder dashboards.",
      "src": "Customer Churn Prediction",
      "tags": [
        "data",
        "ml"
      ]
    },
    {
      "t": "AI Engineer specializing in industrial and manufacturing AI. Builds end-to-end IT-OT data pipelines that ingest high-frequency plant sensor data in real time, trains deep-learning models (PyTorch, TensorFlow, CNNs, LSTM time-series, LiDAR-camera sensor fusion), and applies Generative AI - RAG (LangChain), agentic workflows (LangGraph, MCP), chunking strategies, prompt engineering, and prompt-to-template design - to turn operational data into business decisions. Ships to production with MLOps practices: Docker, Kubernetes with autoscaling, CI/CD, and full observability. Strong foundation in Python, PostgreSQL (SQL) and NoSQL databases, distributed systems, and scalable event-driven architectures.",
      "src": "positioning · master",
      "tags": [
        "master"
      ]
    },
    {
      "t": "AI Engineer specializing in industrial and manufacturing AI (Industry 4.0 / IIoT). Architects end-to-end IT-OT data pipelines that ingest high-frequency plant and engine sensor data over raw TCP/IP in real time, and trains deep-learning time-series models (LSTM, PyTorch) for trend forecasting, anomaly detection and predictive maintenance on live test runs. Designs event-driven publish-subscribe architectures that decouple ingestion, processing and streaming so new sensor types are added by configuration, not code. Applies Generative AI - RAG over technical test reports and agentic natural-language-to-SQL workflows - to put operational data directly in the hands of plant engineers. Ships to production with Docker, Kubernetes autoscaling, CI/CD and full observability.",
      "src": "positioning · industrial",
      "tags": [
        "industrial"
      ]
    },
    {
      "t": "AI Engineer specializing in Generative AI and agentic systems. Builds production RAG pipelines end to end - chunking strategy, embedding selection (Nomic, Gemini), ChromaDB vector stores, cross-encoder reranking and prompt-to-template design - and stateful multi-step agents with LangGraph and MCP that route between tools for natural-language-to-SQL and automated report generation. Serves LLMs across Ollama, OpenAI and Gemini behind a streaming FastAPI layer. Backs it with real deep-learning depth (PyTorch, LSTM, CNNs, BERT) and production MLOps: Docker, Kubernetes with KEDA autoscaling, CI/CD, Prometheus and OpenTelemetry observability.",
      "src": "positioning · genai",
      "tags": [
        "genai"
      ]
    },
    {
      "t": "Computer Vision / Perception Engineer with production deep-learning experience across autonomous-driving and ADAS systems. Built multi-modal 3D object detection fusing LiDAR point clouds (SFA3D) with CNN-based camera detections (YOLOv8) using confidence-weighted IoU association - 92.44% / 80.23% AP (easy / hard) on the KITTI benchmark - including LiDAR-to-camera extrinsic calibration via RANSAC/PROSAC and Gaussian/Weighted NMS post-processing. Shipped a production driver foot-monitoring ADAS system combining segmentation, keypoint and object detection with ZoeDepth monocular depth inference. Strong PyTorch, OpenCV and Open3D foundation, with the MLOps skills (Docker, Kubernetes, ONNX Runtime, CI/CD) to take models from benchmark to production.",
      "src": "positioning · cv",
      "tags": [
        "cv"
      ]
    },
    {
      "t": "ML Platform / MLOps Engineer who builds the infrastructure that serves models at scale. Designed and shipped a horizontally-scalable inference platform - stateless async FastAPI gateway, Redis-Streams broker, shared-nothing worker pool - with dynamic request batching, backpressure with hysteresis, at-least-once delivery via consumer-group reclaim, and O(1) WebSocket result routing that lifted a 120-client ceiling. Runs it on Kubernetes with KEDA queue-depth autoscaling, GitHub Actions CI, Prometheus metrics, OpenTelemetry tracing and ONNX Runtime serving. Backed by real modelling depth in PyTorch (LSTM, CNNs) and production Python/Go distributed-systems experience.",
      "src": "positioning · mlops",
      "tags": [
        "mlops"
      ]
    },
    {
      "t": "Backend Engineer building distributed, event-driven systems in Python and Go. Architected real-time data pipelines ingesting high-frequency sensor streams over raw TCP/IP sockets and delivering them to clients over WebSockets at sub-second latency, with asynchronous processing and multithreaded batched writes that sustain continuous high-volume load. Designs microservice and publish-subscribe architectures, models normalized PostgreSQL schemas alongside NoSQL stores, and secures APIs with JWT and role-based access control. Ships with Docker, Kubernetes, CI/CD and full observability - plus applied ML and GenAI experience for teams building AI-backed products.",
      "src": "positioning · backend",
      "tags": [
        "backend"
      ]
    },
    {
      "t": "Top 10 Finalist - HumanAIze YouData.ai Hackathon (out of 150 teams); built a scalable NLP pipeline for document classification. Hack2skill certificate (ID: 2024H2S06EH10008).",
      "src": "recognition",
      "tags": [
        "achievement"
      ]
    },
    {
      "t": "5th Place - CODE RED 2024 Hackathon (24-hour event); led a team of 4 to build a marine-life classification system using CNNs, real-time image processing, and transfer learning.",
      "src": "recognition",
      "tags": [
        "achievement"
      ]
    },
    {
      "t": "Machine Learning Specialization - Stanford / DeepLearning.AI (Coursera), Dec 2023",
      "src": "recognition",
      "tags": [
        "achievement"
      ]
    },
    {
      "t": "Supervised ML: Regression and Classification  ·  Advanced Learning Algorithms - Stanford / DeepLearning.AI, Nov 2023",
      "src": "recognition",
      "tags": [
        "achievement"
      ]
    },
    {
      "t": "Unsupervised Learning, Recommenders, Reinforcement Learning  ·  Improving Deep Neural Networks - DeepLearning.AI, Dec 2023",
      "src": "recognition",
      "tags": [
        "achievement"
      ]
    },
    {
      "t": "Neural Networks and Deep Learning - DeepLearning.AI, May 2024  ·  OpenCV Bootcamp - OpenCV University, Apr 2025 (Grade: 100%)",
      "src": "recognition",
      "tags": [
        "achievement"
      ]
    },
    {
      "t": "Notice Period: 20-45 days (negotiable)",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    },
    {
      "t": "Expected Ctc: 18-25 LPA depending on role and company tier",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    },
    {
      "t": "Willing To Relocate: Yes - willing to relocate anywhere in India",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    },
    {
      "t": "Work Mode: Open to all - onsite, hybrid and fully remote",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    },
    {
      "t": "Location Summary: Open to roles across India. Priority order: Bengaluru > Pune > Hyderabad > Mumbai > Gurugram/NCR.",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    },
    {
      "t": "Why Looking: Seeking deeper ownership of production AI systems at larger scale, building on my IT-OT pipeline, deep learning and GenAI platform experience.",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    },
    {
      "t": "Total Experience: 1 year 4 months (Apr 2025 - present, incl. 7-month internship converted to full-time)",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    },
    {
      "t": "Highest Qualification: B.E. Information Science and Engineering",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    },
    {
      "t": "International: Open to international roles REMOTE ONLY (no relocation abroad). No visa sponsorship required.",
      "src": "availability",
      "tags": [
        "logistics"
      ]
    }
  ],
  "vocab": {
    "langchain": [
      "Generative AI & Agentic",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "langgraph": [
      "Generative AI & Agentic",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "rag": [
      "Generative AI & Agentic",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "agentic ai (tool-use agents": [
      "Generative AI & Agentic"
    ],
    "mcp)": [
      "Generative AI & Agentic"
    ],
    "chunking strategies": [
      "Generative AI & Agentic"
    ],
    "prompt engineering": [
      "Generative AI & Agentic",
      "positioning · master"
    ],
    "prompt-to-template design": [
      "Generative AI & Agentic"
    ],
    "rerankers": [
      "Generative AI & Agentic"
    ],
    "vector search": [
      "Generative AI & Agentic"
    ],
    "llm & embedding apis (openai": [
      "Generative AI & Agentic"
    ],
    "gemini": [
      "Generative AI & Agentic",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "ollama": [
      "Generative AI & Agentic",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "nomic)": [
      "Generative AI & Agentic"
    ],
    "classification": [
      "Machine Learning"
    ],
    "regression": [
      "Machine Learning"
    ],
    "time-series forecasting (lstm": [
      "Machine Learning"
    ],
    "arima)": [
      "Machine Learning"
    ],
    "ensembles (xgboost": [
      "Machine Learning"
    ],
    "lightgbm": [
      "Machine Learning",
      "Customer Churn Prediction"
    ],
    "adaboost)": [
      "Machine Learning"
    ],
    "feature engineering": [
      "Machine Learning"
    ],
    "data cleaning & pre-processing": [
      "Machine Learning"
    ],
    "smote": [
      "Machine Learning",
      "Customer Churn Prediction"
    ],
    "optuna": [
      "Machine Learning",
      "Customer Churn Prediction"
    ],
    "scikit-learn": [
      "Machine Learning",
      "Sales Trend Analysis & Time-Series Forecasting",
      "Disaster Tweet Classification",
      "Customer Churn Prediction"
    ],
    "pandas": [
      "Machine Learning",
      "Sales Trend Analysis & Time-Series Forecasting",
      "Customer Churn Prediction"
    ],
    "numpy": [
      "Machine Learning",
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "Sales Trend Analysis & Time-Series Forecasting"
    ],
    "statsmodels": [
      "Machine Learning",
      "Sales Trend Analysis & Time-Series Forecasting"
    ],
    "pytorch": [
      "Deep Learning",
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "Foot Monitoring System (ADAS)",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "tensorflow/keras": [
      "Deep Learning",
      "Disaster Tweet Classification"
    ],
    "cnns (yolo": [
      "Deep Learning"
    ],
    "detectron2": [
      "Deep Learning",
      "Foot Monitoring System (ADAS)"
    ],
    "zoedepth)": [
      "Deep Learning"
    ],
    "lstm/rnn time-series models": [
      "Deep Learning"
    ],
    "bert/transformers": [
      "Deep Learning"
    ],
    "transfer learning": [
      "Deep Learning"
    ],
    "lidar-camera sensor fusion": [
      "Deep Learning"
    ],
    "opencv": [
      "Deep Learning",
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "Distributed Multi-Sensor Video Analytics Platform",
      "Foot Monitoring System (ADAS)"
    ],
    "open3d": [
      "Deep Learning",
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)"
    ],
    "docker": [
      "MLOps & Deployment",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "Multi-Vendor Camera Device Management Framework",
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "Distributed Multi-Sensor Video Analytics Platform",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "kubernetes": [
      "MLOps & Deployment",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "keda autoscaling": [
      "MLOps & Deployment"
    ],
    "ci/cd": [
      "MLOps & Deployment",
      "Multi-Vendor Camera Device Management Framework"
    ],
    "prometheus": [
      "MLOps & Deployment",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "opentelemetry": [
      "MLOps & Deployment",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "onnx runtime model serving": [
      "MLOps & Deployment"
    ],
    "structured logging": [
      "MLOps & Deployment"
    ],
    "monitoring": [
      "MLOps & Deployment"
    ],
    "crash-recovery design": [
      "MLOps & Deployment"
    ],
    "python": [
      "Backend & Data Pipelines",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "Multi-Vendor Camera Device Management Framework",
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "Distributed Multi-Sensor Video Analytics Platform",
      "Foot Monitoring System (ADAS)",
      "Sales Trend Analysis & Time-Series Forecasting",
      "Inferno - Distributed ML Inference & Agentic AI Platform",
      "Disaster Tweet Classification",
      "Customer Churn Prediction"
    ],
    "go": [
      "Backend & Data Pipelines",
      "Distributed Multi-Sensor Video Analytics Platform"
    ],
    "java": [
      "Backend & Data Pipelines"
    ],
    "fastapi": [
      "Backend & Data Pipelines",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "Multi-Vendor Camera Device Management Framework",
      "Distributed Multi-Sensor Video Analytics Platform",
      "Foot Monitoring System (ADAS)",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "rest apis": [
      "Backend & Data Pipelines",
      "Distributed Multi-Sensor Video Analytics Platform"
    ],
    "websockets": [
      "Backend & Data Pipelines",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "Distributed Multi-Sensor Video Analytics Platform",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "tcp/ip sockets": [
      "Backend & Data Pipelines",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "microservices": [
      "Backend & Data Pipelines",
      "Distributed Multi-Sensor Video Analytics Platform"
    ],
    "event-driven pub-sub": [
      "Backend & Data Pipelines"
    ],
    "redis streams": [
      "Backend & Data Pipelines"
    ],
    "asyncio": [
      "Backend & Data Pipelines",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "jwt": [
      "Backend & Data Pipelines",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "rbac": [
      "Backend & Data Pipelines",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "postgresql": [
      "Databases & Cloud",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "Multi-Vendor Camera Device Management Framework",
      "Distributed Multi-Sensor Video Analytics Platform",
      "Foot Monitoring System (ADAS)"
    ],
    "nosql": [
      "Databases & Cloud"
    ],
    "mysql": [
      "Databases & Cloud"
    ],
    "chromadb": [
      "Databases & Cloud",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "aws": [
      "Databases & Cloud",
      "Distributed Multi-Sensor Video Analytics Platform",
      "Foot Monitoring System (ADAS)"
    ],
    "linux": [
      "Databases & Cloud"
    ],
    "git": [
      "Databases & Cloud"
    ],
    "react.js": [
      "Frontend",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "typescript": [
      "Frontend",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "redux toolkit": [
      "Frontend",
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "html": [
      "Frontend"
    ],
    "css": [
      "Frontend"
    ],
    "data structures": [
      "Core CS"
    ],
    "oop": [
      "Core CS"
    ],
    "distributed systems": [
      "Core CS"
    ],
    "system design": [
      "Core CS"
    ],
    "concurrency": [
      "Core CS"
    ],
    "operating systems": [
      "Core CS"
    ],
    "computer networks": [
      "Core CS"
    ],
    "lstm": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "openai": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "mongodb": [
      "Multi-Vendor Camera Device Management Framework"
    ],
    "react": [
      "Multi-Vendor Camera Device Management Framework",
      "Foot Monitoring System (ADAS)",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "oop design patterns": [
      "Multi-Vendor Camera Device Management Framework"
    ],
    "yolov8": [
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)",
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "sfa3d": [
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)"
    ],
    "slam": [
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)"
    ],
    "ransac/prosac": [
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)"
    ],
    "yolov11": [
      "Foot Monitoring System (ADAS)"
    ],
    "zoedepth": [
      "Foot Monitoring System (ADAS)"
    ],
    "arima": [
      "Sales Trend Analysis & Time-Series Forecasting"
    ],
    "matplotlib": [
      "Sales Trend Analysis & Time-Series Forecasting"
    ],
    "seaborn": [
      "Sales Trend Analysis & Time-Series Forecasting"
    ],
    "redis": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "onnx runtime": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "faster-whisper": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "sentence-transformers": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "mcp": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "keda": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "github actions": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "nltk": [
      "Disaster Tweet Classification"
    ],
    "bert": [
      "Disaster Tweet Classification"
    ],
    "tf-idf": [
      "Disaster Tweet Classification"
    ],
    "xgboost": [
      "Customer Churn Prediction"
    ],
    "adaboost": [
      "Customer Churn Prediction"
    ],
    "anomaly detection": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "predictive maintenance": [
      "positioning · industrial"
    ],
    "time-series": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "forecasting": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "sensor fusion": [
      "positioning · master"
    ],
    "real-time": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "streaming": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "event-driven": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "pub-sub": [
      "Backend & Data Pipelines"
    ],
    "backpressure": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "autoscaling": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "observability": [
      "positioning · master"
    ],
    "chunking": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "reranking": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "natural-language-to-sql": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "calibration": [
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)"
    ],
    "segmentation": [
      "Foot Monitoring System (ADAS)"
    ],
    "object detection": [
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)"
    ],
    "keypoint detection": [
      "Foot Monitoring System (ADAS)"
    ],
    "depth": [
      "Foot Monitoring System (ADAS)"
    ],
    "class imbalance": [
      "Customer Churn Prediction"
    ],
    "hyperparameter": [
      "Customer Churn Prediction"
    ],
    "model serving": [
      "MLOps & Deployment"
    ],
    "batching": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "load": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "role-based access control": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "it-ot": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "telemetry": [
      "Inferno - Distributed ML Inference & Agentic AI Platform"
    ],
    "tcp/ip": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "vector store": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "embeddings": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "agentic": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "distributed": [
      "Multi-Vendor Camera Device Management Framework"
    ],
    "multithreaded": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "asynchronous": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "schema": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "ingestion": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "dashboards": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "industrial": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "manufacturing": [
      "positioning · master"
    ],
    "sensor": [
      "Real-Time Engine Test-Bed Monitoring & Telemetry Platform"
    ],
    "point cloud": [
      "positioning · cv"
    ],
    "annotation": [
      "Foot Monitoring System (ADAS)"
    ],
    "inference": [
      "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI)"
    ]
  },
  "aliases": {
    "k8s": "kubernetes",
    "kubernetes": "kubernetes",
    "ci/cd": "ci/cd",
    "cicd": "ci/cd",
    "llm": "prompt engineering",
    "llms": "prompt engineering",
    "genai": "rag",
    "generative ai": "rag",
    "gen ai": "rag",
    "vector database": "chromadb",
    "vector db": "chromadb",
    "embeddings": "rag",
    "time series": "time-series",
    "timeseries": "time-series",
    "forecast": "forecasting",
    "iiot": "industrial",
    "iot": "industrial",
    "industry 4.0": "industrial",
    "computer vision": "opencv",
    "cv": "opencv",
    "object detection": "yolo",
    "deep learning": "pytorch",
    "neural network": "pytorch",
    "mlops": "docker",
    "model serving": "onnx runtime",
    "microservice": "microservices",
    "rest": "rest apis",
    "api": "rest apis",
    "sql": "postgresql",
    "postgres": "postgresql",
    "nosql": "mongodb",
    "aws": "aws",
    "cloud": "aws",
    "pub/sub": "event-driven pub-sub",
    "pubsub": "event-driven pub-sub",
    "kafka": "",
    "spark": "",
    "azure": "",
    "gcp": ""
  },
  "achievements": [
    "Top 10 Finalist - HumanAIze YouData.ai Hackathon (out of 150 teams); built a scalable NLP pipeline for document classification. Hack2skill certificate (ID: 2024H2S06EH10008).",
    "5th Place - CODE RED 2024 Hackathon (24-hour event); led a team of 4 to build a marine-life classification system using CNNs, real-time image processing, and transfer learning.",
    "Machine Learning Specialization - Stanford / DeepLearning.AI (Coursera), Dec 2023",
    "Supervised ML: Regression and Classification  ·  Advanced Learning Algorithms - Stanford / DeepLearning.AI, Nov 2023",
    "Unsupervised Learning, Recommenders, Reinforcement Learning  ·  Improving Deep Neural Networks - DeepLearning.AI, Dec 2023",
    "Neural Networks and Deep Learning - DeepLearning.AI, May 2024  ·  OpenCV Bootcamp - OpenCV University, Apr 2025 (Grade: 100%)"
  ],
  "history": [
    {
      "kind": "education",
      "start": "2018-04",
      "end": "2019-04",
      "label": "DAV Public School, Jamshedpur",
      "detail": "CBSE Class 10: 92.4%"
    },
    {
      "kind": "education",
      "start": "2020-04",
      "end": "2021-05",
      "label": "DAV Public School, Jamshedpur",
      "detail": "CBSE Class 12: 92.4%"
    },
    {
      "kind": "education",
      "start": "2021-12",
      "end": "2025-07",
      "label": "Bangalore Institute of Technology",
      "detail": "B.E. in Information Science and Engineering (CGPA: 8.6)"
    },
    {
      "kind": "cert",
      "start": "2023-11",
      "end": null,
      "label": "Supervised Machine Learning: Regression and Classification",
      "detail": "Stanford University / DeepLearning.AI (Coursera)"
    },
    {
      "kind": "cert",
      "start": "2023-11",
      "end": null,
      "label": "Advanced Learning Algorithms",
      "detail": "Stanford University / DeepLearning.AI (Coursera)"
    },
    {
      "kind": "cert",
      "start": "2023-12",
      "end": null,
      "label": "Machine Learning Specialization",
      "detail": "Stanford University / DeepLearning.AI (Coursera)"
    },
    {
      "kind": "cert",
      "start": "2023-12",
      "end": null,
      "label": "Unsupervised Learning, Recommenders, Reinforcement Learning",
      "detail": "Stanford University / DeepLearning.AI (Coursera)"
    },
    {
      "kind": "cert",
      "start": "2023-12",
      "end": null,
      "label": "Improving Deep Neural Networks: Hyperparameter Tuning, Regularization & Optimization",
      "detail": "DeepLearning.AI (Coursera)"
    },
    {
      "kind": "award",
      "start": "2024-03",
      "end": null,
      "label": "5th place — CODE RED 24-hour hackathon",
      "detail": "Led a team of 4; marine-life classification with CNNs"
    },
    {
      "kind": "cert",
      "start": "2024-05",
      "end": null,
      "label": "Neural Networks and Deep Learning",
      "detail": "DeepLearning.AI (Coursera)"
    },
    {
      "kind": "award",
      "start": "2024-06",
      "end": null,
      "label": "Top 10 of 150 — HumanAIze YouData.ai",
      "detail": "Scalable NLP pipeline for document classification"
    },
    {
      "kind": "role",
      "start": "2025-04",
      "end": "2025-11",
      "label": "Machine Learning Intern — Deevia Software",
      "detail": "3D Object Detection via LiDAR-Camera Sensor Fusion (KITTI), Distributed Multi-Sensor Video Analytics Platform, Foot Monitoring System (ADAS), Sales Trend Analysis & Time-Series Forecasting"
    },
    {
      "kind": "cert",
      "start": "2025-04",
      "end": null,
      "label": "OpenCV Bootcamp",
      "detail": "OpenCV University"
    },
    {
      "kind": "role",
      "start": "2025-11",
      "end": null,
      "label": "Graduate Trainee Engineer — Deevia Software",
      "detail": "Real-Time Engine Test-Bed Monitoring & Telemetry Platform, Multi-Vendor Camera Device Management Framework"
    }
  ],
  "certs": [
    {
      "name": "Machine Learning Specialization",
      "issuer": "Stanford University / DeepLearning.AI (Coursera)",
      "date": "December 2023",
      "id": "7EF786TYXS89",
      "url": "https://www.coursera.org/account/accomplishments/specialization/7EF786TYXS89"
    },
    {
      "name": "Supervised Machine Learning: Regression and Classification",
      "issuer": "Stanford University / DeepLearning.AI (Coursera)",
      "date": "November 2023",
      "id": "WFWDKEA3PC4E",
      "url": "https://www.coursera.org/account/accomplishments/verify/WFWDKEA3PC4E"
    },
    {
      "name": "Advanced Learning Algorithms",
      "issuer": "Stanford University / DeepLearning.AI (Coursera)",
      "date": "November 2023",
      "id": "GHT8X2JWMCT8",
      "url": "https://www.coursera.org/account/accomplishments/verify/GHT8X2JWMCT8"
    },
    {
      "name": "Unsupervised Learning, Recommenders, Reinforcement Learning",
      "issuer": "Stanford University / DeepLearning.AI (Coursera)",
      "date": "December 2023",
      "id": "7PJTJ88S3BP4",
      "url": "https://www.coursera.org/account/accomplishments/verify/7PJTJ88S3BP4"
    },
    {
      "name": "Neural Networks and Deep Learning",
      "issuer": "DeepLearning.AI (Coursera)",
      "date": "May 2024",
      "id": "7AW6UF33TWWA",
      "url": "https://www.coursera.org/account/accomplishments/verify/7AW6UF33TWWA"
    },
    {
      "name": "Improving Deep Neural Networks: Hyperparameter Tuning, Regularization & Optimization",
      "issuer": "DeepLearning.AI (Coursera)",
      "date": "December 2023",
      "id": "HHKRTRSAWWMD",
      "url": "https://www.coursera.org/account/accomplishments/verify/HHKRTRSAWWMD"
    },
    {
      "name": "OpenCV Bootcamp",
      "issuer": "OpenCV University",
      "date": "April 2025",
      "id": "Grade: 100%",
      "url": "https://www.linkedin.com/in/sagar-chaudhary777/"
    }
  ],
  "education": [
    {
      "institution": "Bangalore Institute of Technology",
      "detail": "B.E. in Information Science and Engineering (CGPA: 8.6)",
      "dates": "Dec 2021 - Jul 2025"
    },
    {
      "institution": "DAV Public School, Jamshedpur",
      "detail": "CBSE Class 12: 92.4%",
      "dates": "Apr 2020 - May 2021"
    },
    {
      "institution": "DAV Public School, Jamshedpur",
      "detail": "CBSE Class 10: 92.4%",
      "dates": "Apr 2018 - Apr 2019"
    }
  ]
};
